"""Advanced model service for difficult SQL routing and self-correction."""

import logging
from openai import AsyncOpenAI

from ..config import BackendSettings


class AdvancedSqlService:
    def __init__(self, settings: BackendSettings, logger: logging.Logger):
        self.settings = settings
        self.logger = logger

        # Initialize the OpenAI-compatible HTTP client
        self.client = AsyncOpenAI(
            api_key=settings.qwen3_api_token or "sk-dummy",
            base_url=settings.qwen3_base_url,
        )
        self.model = settings.advanced_model_name

    def _extract_sql(self, text: str) -> str:
        """Extract SQL from markdown formatting if present."""
        text = text.strip()
        import re
        match = re.search(r"```(?:sql)?\s*(.*?)\s*```", text, re.DOTALL | re.IGNORECASE)
        if match:
            return match.group(1).strip()
        return text

    async def improve_sql(self, query: str, schema: str, previous_sql: str) -> str:
        """Enhance a SQL query generated by another model for 'hard' labeled inputs."""
        self.logger.info("Improving SQL using advanced model %s", self.model)
        
        system_prompt = (
            "You are an expert Data Engineer. "
            "A base SQL query was generated for a complex question, but it may be suboptimal or incorrect. "
            "Your task is to refine and improve the SQL query to answer the user's question perfectly, "
            "using ONLY the tables and columns provided in the schema.\n"
            "Return ONLY the raw, improved SQL query inside a markdown ```sql block. Do not provide ANY explanation or conversational text."
        )
        
        user_prompt = (
            f"Schema:\n{schema}\n\n"
            f"Question:\n{query}\n\n"
            f"Base SQL Query:\n```sql\n{previous_sql}\n```\n\n"
            "Please provide the corrected/improved SQL query."
        )
        
        try:
            response = await self.client.chat.completions.create(
                model=self.model,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt},
                ],
                temperature=0.0,
                max_tokens=1024,
            )
            raw_output = response.choices[0].message.content or ""
            return self._extract_sql(raw_output)
        except Exception as exc:
            self.logger.error("Advanced SQL generation failed: %s", exc)
            raise

    async def fix_sql(self, query: str, schema: str, bad_sql: str, error_msg: str) -> str:
        """Self-Correction loop for when SQL execution fails."""
        self.logger.info("Attempting to fix SQL using advanced model %s", self.model)
        
        system_prompt = (
            "You are an expert Data Engineer. "
            "A previous SQL query failed to run on SQLite due to an execution error. "
            "Your task is to fix the SQL query using the provided schema to answer the user's question.\n"
            "Return ONLY the corrected raw SQL query inside a markdown ```sql block. Do not provide ANY explanation or conversational text."
        )
        
        user_prompt = (
            f"Schema:\n{schema}\n\n"
            f"Question:\n{query}\n\n"
            f"Bad SQL Query:\n```sql\n{bad_sql}\n```\n\n"
            f"Execution Error:\n{error_msg}\n\n"
            "Fix the query so it runs successfully."
        )
        
        try:
            response = await self.client.chat.completions.create(
                model=self.model,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt},
                ],
                temperature=0.0,
                max_tokens=1024,
            )
            raw_output = response.choices[0].message.content or ""
            return self._extract_sql(raw_output)
        except Exception as exc:
            self.logger.error("Advanced SQL self-correction failed: %s", exc)
            raise
